In [17]:
import pandas as pd

In [18]:
dfTest = pd.read_csv('../data/testWithMean.csv',nrows=100000)
dfTrain = pd.read_csv('../data/trainWithMean.csv',nrows=100000)

In [25]:
dfTest.columns

Index(['srch_id', 'date_time', 'site_id', 'visitor_location_country_id',
       'visitor_hist_starrating', 'visitor_hist_adr_usd', 'prop_country_id',
       'prop_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool',
       'prop_location_score1', 'prop_location_score2',
       'prop_log_historical_price', 'price_usd', 'promotion_flag',
       'srch_destination_id', 'srch_length_of_stay', 'srch_booking_window',
       'srch_adults_count', 'srch_children_count', 'srch_room_count',
       'srch_saturday_night_bool', 'srch_query_affinity_score',
       'orig_destination_distance', 'random_bool', 'comp1_rate', 'comp1_inv',
       'comp1_rate_percent_diff', 'comp2_rate', 'comp2_inv',
       'comp2_rate_percent_diff', 'comp3_rate', 'comp3_inv',
       'comp3_rate_percent_diff', 'comp4_rate', 'comp4_inv',
       'comp4_rate_percent_diff', 'comp5_rate', 'comp5_inv',
       'comp5_rate_percent_diff', 'comp6_rate', 'comp6_inv',
       'comp6_rate_percent_diff', 'comp7_rate', 'comp7_inv',
       'comp7_rate_percent_diff', 'comp8_rate', 'comp8_inv',
       'comp8_rate_percent_diff', 'mean_prop_starrating',
       'mean_prop_review_score', 'mean_prop_brand_bool',
       'mean_prop_location_score1', 'mean_prop_location_score2',
       'mean_prop_log_historical_price', 'cluster__0', 'cluster__1',
       'cluster__2', 'cluster__3', 'cluster__4', 'cluster__5',
       'booking_prop_dest_mean', 'booking_prop_total_mean',
       'diff_distance_orig'],
      dtype='object')

In [31]:
pd.concat([dfTest[['srch_id','prop_id','booking_prop_dest_mean', 'booking_prop_total_mean',
       'diff_distance_orig','orig_destination_distance']],dfTrain[['srch_id','prop_id','booking_prop_dest_mean', 'booking_prop_total_mean',
       'diff_distance_orig','orig_destination_distance']]],axis=0).to_csv("overview2.csv",index=False)

In [21]:
dfTest.head(100)

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,mean_prop_log_historical_price,cluster__0,cluster__1,cluster__2,cluster__3,cluster__4,cluster__5,booking_prop_dest_mean,booking_prop_total_mean,diff_distance_orig
0,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,3180,3,4.5,...,4.196765,1,0,0,0,0,0,0.077778,0.043011,NaN
1,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,5543,3,4.5,...,4.283044,1,0,0,0,0,0,0.142857,0.053279,NaN
2,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,14142,2,3.5,...,3.786120,0,0,0,0,0,1,0.000000,0.013423,NaN
3,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,22393,3,4.5,...,4.295411,1,0,0,0,0,0,0.026316,0.013793,NaN
4,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,24194,3,4.5,...,4.011241,1,0,0,0,0,0,0.010870,0.014634,NaN
5,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,28181,3,4.5,...,4.047179,1,0,0,0,0,0,0.136842,0.075000,NaN
6,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,34263,3,4.5,...,3.982442,1,0,0,0,0,0,0.022727,0.032086,NaN
7,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,37567,2,4.5,...,3.614970,0,0,1,0,0,0,0.000000,0.012579,NaN
8,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,50162,2,3.5,...,3.707043,0,0,0,0,0,1,0.053763,0.034247,NaN
9,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,54937,3,4.0,...,4.021068,1,0,0,0,0,0,0.086022,0.050891,NaN
10,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,56050,3,4.0,...,4.063620,1,0,0,0,0,0,0.012821,0.028986,NaN
11,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,61632,0,0.0,...,3.959375,0,0,0,0,1,0,0.000000,0.000000,NaN
12,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,61934,3,4.5,...,4.122967,1,0,0,0,0,0,0.067416,0.027701,NaN
13,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,63894,3,4.5,...,4.236386,1,0,0,0,0,0,0.000000,0.018293,NaN
14,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,72090,3,4.0,...,4.272465,1,0,0,0,0,0,0.000000,0.005780,NaN
15,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,73666,3,4.5,...,4.066134,1,0,0,0,0,0,0.011111,0.005128,NaN
16,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,74045,3,4.0,...,3.906752,1,0,0,0,0,0,0.055556,0.032558,NaN
17,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,78599,4,4.5,...,4.274106,1,0,0,0,0,0,0.023256,0.030568,NaN
18,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,82231,3,4.5,...,4.264088,1,0,0,0,0,0,0.000000,0.011364,NaN
19,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,89466,2,3.0,...,4.334161,0,1,0,0,0,0,0.000000,0.000000,NaN
20,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,90385,3,4.5,...,3.725097,1,0,0,0,0,0,0.035714,0.033019,NaN
21,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,94729,3,4.5,...,4.333914,1,0,0,0,0,0,0.037975,0.026738,NaN
22,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,95031,3,3.5,...,3.743874,1,0,0,0,0,0,0.020833,0.021277,NaN
23,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,99484,3,4.0,...,3.921837,1,0,0,0,0,0,0.063830,0.047753,NaN
24,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,123675,3,4.5,...,4.355498,1,0,0,0,0,0,0.000000,0.000000,NaN
25,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,128085,2,3.0,...,3.596496,0,0,0,0,0,1,0.011494,0.020101,NaN
26,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,128871,2,3.0,...,3.759836,0,0,0,0,0,1,0.000000,0.006536,NaN
27,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,134992,2,5.0,...,3.937655,0,0,0,0,0,1,0.000000,0.000000,NaN
28,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,139162,3,4.5,...,4.135341,1,0,0,0,0,0,0.012346,0.012500,NaN
29,3,2013-01-14 10:11:09,5,219,NaN,NaN,219,6533,4,4.0,...,4.303000,1,0,0,0,0,0,NaN,0.064103,0.766813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,20852,3,0.0,...,4.482778,0,0,1,0,0,0,0.045455,0.027027,NaN
71,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,28031,3,4.0,...,4.455059,0,0,1,0,0,0,0.024390,0.008696,NaN
72,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,28570,3,4.0,...,4.307838,0,0,1,0,0,0,0.051282,0.041096,NaN
73,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,36908,2,4.0,...,3.373590,0,0,1,0,0,0,0.000000,0.000000,NaN
74,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,42035,3,4.0,...,4.395574,1,0,0,0,0,0,0.029412,0.025641,NaN
75,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,48813,3,0.0,...,4.532424,0,0,1,0,0,0,0.000000,0.000000,NaN
76,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,55244,3,3.0,...,4.028901,1,0,0,0,0,0,0.042553,0.022222,NaN
77,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,63861,3,0.0,...,4.240598,1,0,0,0,0,0,0.000000,0.000000,NaN
78,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,80954,2,0.0,...,4.206857,0,0,1,0,0,0,0.000000,0.000000,NaN
79,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,85859,2,4.0,...,3.690533,0,0,1,0,0,0,0.000000,0.000000,NaN
80,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,88320,2,0.0,...,4.427500,0,1,0,0,0,0,0.000000,0.000000,NaN
81,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,89375,2,4.0,...,3.674541,0,1,0,0,0,0,0.000000,0.000000,NaN
82,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,92347,3,4.0,...,3.948713,0,0,1,0,0,0,0.000000,0.000000,NaN
83,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,95338,3,4.5,...,3.796957,0,0,1,0,0,0,0.033333,0.029412,NaN
84,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,97821,3,0.0,...,4.200950,0,1,0,0,0,0,0.042553,0.033333,NaN
85,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,100665,3,0.0,...,4.153983,0,0,1,0,0,0,0.111111,0.088889,NaN
86,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,107796,2,3.5,...,3.919804,0,0,1,0,0,0,0.000000,0.000000,NaN
87,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,110442,3,4.0,...,4.052768,0,0,1,0,0,0,0.133333,0.130435,NaN
88,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,112814,2,0.0,...,3.698283,0,0,1,0,0,0,0.000000,0.020408,NaN
89,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,113456,3,4.5,...,4.318046,1,0,0,0,0,0,0.042553,0.032609,NaN
90,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,130919,2,4.5,...,4.212903,0,0,1,0,0,0,0.000000,0.000000,NaN
91,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,139434,3,4.0,...,4.093109,0,0,1,0,0,0,0.030303,0.037736,NaN
92,7,2012-12-16 08:51:29,24,99,NaN,NaN,216,140094,3,5.0,...,4.151690,0,0,1,0,0,0,0.000000,0.000000,NaN
93,10,2013-03-01 11:27:11,14,100,NaN,NaN,100,1147,3,4.0,...,4.152968,1,0,0,0,0,0,0.000000,0.032967,3.917380
94,10,2013-03-01 11:27:11,14,100,NaN,NaN,100,10987,3,3.5,...,3.942818,1,0,0,0,0,0,0.111111,0.014184,3.917380
95,10,2013-03-01 11:27:11,14,100,NaN,NaN,100,11203,2,2.5,...,3.889577,0,0,0,0,0,1,0.000000,0.000000,3.917380
96,10,2013-03-01 11:27:11,14,100,NaN,NaN,100,23777,4,4.0,...,4.340503,1,0,0,0,0,0,0.000000,0.047872,3.917380
97,10,2013-03-01 11:27:11,14,100,NaN,NaN,100,31281,3,4.5,...,4.315897,1,0,0,0,0,0,0.000000,0.036496,3.917380
98,10,2013-03-01 11:27:11,14,100,NaN,NaN,100,37420,3,4.0,...,4.076579,1,0,0,0,0,0,0.000000,0.009346,3.917380
99,10,2013-03-01 11:27:11,14,100,NaN,NaN,100,37616,3,4.0,...,4.279416,1,0,0,0,0,0,0.000000,0.000000,3.917380